POST http://localhost:3000/api/user/register HTTP/1.1
Content-type: application/json

{    
   "name": "name",
   "lastName": "lastName",
   "email":"name@email.pl",
   "password":"password"
}

###

GET http://localhost:3000/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhYUB5YWhvby5jb20iLCJhbnlEYXRhIjoiMTIzIiwiaWF0IjoxNjUzMzA4OTEzLCJleHAiOjE2NTMzMDkwMzN9.kUCzgNMp9eUU7JMe-bcEKvJ8CN16NNl0C2CISHONr44 HTTP/1.1

###